// Original synthetic KID-format instructions, no commercial content.
import{test}from'node:test';import assert from'node:assert/strict';import{Remember11Engine}from'../web/adapters/remember11-engine.mjs';
const name='00000-TEST.BIP',hash='a'.repeat(64),ins=(offset,op,sub,words,extra={})=>({offset,id:`${name}:${offset.toString(16).padStart(4,'0')}`,op,sub,words,next:offset+2,name:'synthetic',...extra});
function fixture(){const rows=[ins(0,9,0,[9,0x6001,1]),ins(2,115,0,[115],{text:'独自のテスト。%K%P',voice:65535,readId:1}),ins(4,116,2,[116],{destination:0x6002,options:[{text:'進む',condition:1,target:6},{text:'戻る',condition:1,target:10}]}),ins(6,9,1,[9,0x6001,2]),ins(8,3,0,[3],{target:12}),ins(10,9,2,[9,0x6001,1]),ins(12,115,0,[115],{text:'同じ文章。%K%P',voice:65535,readId:2}),ins(14,1,1,[257])];const data={format:'vnkit.remember11-script',version:1,source:name,sha256:hash,instructions:Object.fromEntries(rows.map(i=>[i.offset,i]))};const c={format:'vnkit.content',version:1,id:'synthetic-kid-test',assets:{},runtime:{id:'remember11-ps2-kid',version:1,entry:name,scripts:{[name]:{url:'test.json',sha256:hash}},byResource:{0:name}}};return{c,data};}
async function setup(){const{c,data}=fixture();return{e:await Remember11Engine.create(c,{loadJSON:async()=>structuredClone(data),makeId:()=> 'occurrence'}),c,data};}
test('both original branches preserve state across save/restore',async()=>{const{e,c,data}=await setup();await e.run();await e.advance();const saved=e.save();for(const [choice,value]of[['0',3],['1',0]]){await e.restore(saved);await e.advance(choice);assert.equal(e.value(0x6001),value);const r=await Remember11Engine.create(c,{loadJSON:async()=>data});await r.restore(e.save());assert.deepEqual(r.state,e.state);assert.equal((await r.advance()).pending.kind,'end');}});
test('failed unknown instruction rolls back the full visible checkpoint',async()=>{const{e}=await setup();await e.run();const before=e.save();e.scripts[name].instructions[4].op=999;await assert.rejects(e.advance(),/Unsupported command/);assert.deepEqual(e.save().state,before.state);});
test('signed16, flags, failed save import and current text identity',async()=>{const{e}=await setup();e.assign(0x6003,32768);assert.equal(e.value(0x6003),-32768);e.assign(0xa007,3);assert.equal(e.value(0xa007),1);await e.run();const before=e.save();await assert.rejects(e.restore({...before,gameId:'wrong'}),/Incompatible/);const forged=structuredClone(before);forged.state.pending.text='forged';await assert.rejects(e.restore(forged),/differs/);assert.deepEqual(e.save().state,before.state);});
test('native waits and current occurrence survive restore; progress stays separate',async()=>{const{e,c,data}=await setup();data.instructions[2]=ins(2,12,0,[12,30]);e.scripts={};await e.run();assert.equal(e.current.kind,'wait');const saved=e.save();await e.restore(saved);assert.deepEqual(e.save().state,saved.state);e.markRouteComplete('kokoro');const p=e.progressSnapshot();const fresh=await Remember11Engine.create(c,{loadJSON:async()=>data});fresh.applyProgress(p);assert.equal(fresh.newGameEntries()[1].id,'satoru');assert.deepEqual(fresh.state.vars.local,{});assert.equal(fresh.routeProgress()[0].manual,true);});
test('portrait centre anchor preserves complete native frame and saved coordinates',async()=>{const{e}=await setup();e.content.assets['image:12288']={type:'image',url:'original.png',width:640,height:448};e.state.graphics[1]={asset:'image:12288',x:320,y:14,z:1,visible:true};e.compose();assert.equal(e.state.scene.layers[0].x,0);assert.equal(e.state.scene.layers[0].y,-14/448*100);assert.equal(e.state.graphics[1].x,320);});
test('forged choice and malformed progress are rejected atomically',async()=>{const{e}=await setup();await e.run();await e.advance();const before=e.save(),forged=structuredClone(before);forged.state.pending.options[0].target=10;await assert.rejects(e.restore(forged),/choices differ/);assert.deepEqual(e.save().state,before.state);const p=e.progressSnapshot();p.globals.globalBits[84]=1;p.globals.catalog={};assert.throws(()=>e.applyProgress(p),/catalog/);assert.deepEqual(e.save().state,before.state);});
test('completed-route read status uses only a signature-bound verified path',async()=>{const{e}=await setup(),id=`${name}:0002`;e.loadJSON=async()=>({format:'vnkit.read-paths',version:1,gameId:e.content.id,gameSignature:e.signature,paths:{kokoro:{ids:[id]}}});await e.loadReadPaths();assert.equal(e.isInheritedRead(id),false);e.markRouteComplete('kokoro');assert.equal(e.isInheritedRead(id),true);assert.equal(e.isInheritedRead(`${name}:000c`),false);e.loadJSON=async()=>({format:'wrong'});await e.loadReadPaths();assert.equal(e.isInheritedRead(id),false);assert.match(e.readPathWarning,/unavailable/);});
test('legacy native read flags migrate to compact words without changing the source read count',async()=>{const{e}=await setup();await e.run();const old=e.save();old.state.catalog.read={[`${name}:0`]:true,[`${name}:31`]:true,[`${name}:32`]:true};await e.restore(old);assert.deepEqual(e.state.catalog.read,{'0:0':2147483649,'0:1':1});e.calculate({sub:24,words:[9,0x6007,0]});assert.equal(e.value(0x6007),3);const p=e.progressSnapshot();p.globals.catalog.read={[`${name}:31`]:true};e.applyProgress(p);assert.deepEqual(e.state.catalog.read,{'0:0':2147483648});});
